module.exports = {
  auth: {
    language: "javascript",
    validate_doc_update: "function (newDoc, oldDoc, userCtx, secObj) {\n  if (!userCtx || userCtx.roles.indexOf('_admin') !== -1 || userCtx.roles.indexOf('doc_full') !== -1) {return}\n  var msg = {forbidden: 'Недостаточно прав для изменения документа: ' + newDoc._id};\n  if (userCtx.roles.indexOf('doc_editor') !== -1) {\n    if (newDoc._id.substr(0, 19) == 'cat.scheme_settings' && newDoc.user != userCtx.name) {\n      throw(msg)\n    }\n    if ([\n      'registers_correction',\n      'purchase',\n      'work_centers_performance', \n      'work_centers_task', \n      'credit_cash_order',\n      'debit_bank_order',\n      'credit_bank_order',\n      'debit_cash_order',\n      'credit_cash_order',\n      'selling'].some(function (name) {\n          if (newDoc._id.indexOf(name) != -1) return true\n        })) {\n      throw(msg)\n    }\n  }\n  else {\n    throw(msg)\n  }\n}",
    filters: {
      by_partner: "function (doc, req) {\n  if (doc._id == '_design/server'){\n    return false\n  }\n  if (!req.query.partner || !req.query.department || !req.query.price_type){\n    return true\n  }\n  if (doc.class_name == 'doc.nom_prices_setup') {\n    return req.query.price_type.match(doc.price_type)\n  }\n  if (doc.class_name == 'ireg.margin_coefficients') {\n    if(!req.query.parameters_keys){\n      return true\n    }\n    var key = doc._id.split('|')[1].split('¶')[1];\n    return key == '00000000-0000-0000-0000-000000000000' || req.query.parameters_keys.match(key)\n  }\n  if (doc.class_name == 'cat.nom_prices_types') {\n    return req.query.price_type.match(doc._id.substr(21))\n  }\n  if (doc.class_name == 'cat.partners') {\n    return doc.is_folder || req.query.partner.match(doc._id.substr(13))\n  }\n  if (doc.class_name == 'cat.contracts') {\n    return doc.is_folder || req.query.partner.match(doc.owner)\n  }\n  if (doc.class_name == 'cat.divisions') {\n    return req.query.department.match(doc._id.substr(14)) || req.query.department.match(doc.parent)\n  }\n  if (doc.class_name == 'cat.partner_bank_accounts') {\n    return req.query.partner.match(doc.owner)\n  }\n  if (doc.class_name == 'cat.parameters_keys') {\n    if(!req.query.parameters_keys){\n      return true\n    }\n    var key = doc._id.substr(20);\n    if(req.query.parameters_keys.match(key)){\n      return true\n    }\n    if(doc.params.some(function(row){\n      if(row.property == 'Контрагент'){\n        return !req.query.partner.match(row.value)\n      }\n    })){\n      return false\n    }\n    return true\n  }\n  if (doc._id[0] == '_' || !doc.partner || doc.partner == '00000000-0000-0000-0000-000000000000'){\n    return true\n  }\n  return req.query.partner.match(doc.partner) && (!doc.department || doc.department == '00000000-0000-0000-0000-000000000000' || req.query.department.match(doc.department))\n}"
    }
  }
};
